apiVersion: controller.k8s.do/v1
kind: OpenGauss
metadata:
  name: b
  namespace: test
spec:
  image: ructrx/og-ivld-buf2:1.0.1
  imagePullPolicy: IfNotPresent
  opengauss:
    master:
      replicas: 1
    mycat:
      image: yanglibao/mycat:v7.3
      replicas: 1
    origin:
      mycatCluster: a-mycat-sts
      pvc: b-pvc
      master: a
    tables:
    - sbtest6
    - sbtest7
    - sbtest8
    - sbtest9
    - sbtest10
    worker:
      replicas: 4
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 50Gi
    limits:
      cpu: 1500m
      memory: 2Gi
