apiVersion: controller.k8s.do/v1
kind: OpenGauss
metadata:
  name: d
  namespace: test
spec:
  image: ructrx/og-ivld-buf2:1.0.1
  imagePullPolicy: IfNotPresent
  opengauss:
    master:
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 2Gi
    workerSmall:
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 2Gi
    workerMid:
      replicas: 1
      resources:
        limits:
          cpu: 2000m
          memory: 4Gi
        requests:
          cpu: 2000m
          memory: 4Gi
    workerLarge:
      replicas: 1
      resources:
        limits:
          cpu: 4000m
          memory: 8Gi
        requests:
          cpu: 4000m
          memory: 8Gi
    shardingsphere:
      image: apache/shardingsphere-proxy:latest
      replicas: 1 
      resources:
        limits:
          cpu: 4000m
          memory: 8Gi
        requests:
          cpu: 4000m
          memory: 8Gi           
  storageClassName: opengauss-newlocal
  resources:
    requests:
      storage: 50Gi
    limits:
      cpu: 1500m
      memory: 2Gi
