apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-pvc
  namespace: test
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
