name: go build

on:
  push:
    branches:
    - master
  pull_request:
    branches: 
    - master

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
  
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Build
      run: go build -v -o controller .

  build_container_image:
    name: Build image
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2 
    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: waterme7on/opengauss-operator
        registry: docker.io
        dockerfile: Dockerfile
        addTimestamp: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
