name: go build

on:
  push:
    branches:
    - master
  pull_request:
    branches: 
    - master

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
  
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Build
      run: go build -v -o controller .

  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
